#!/usr/bin/sh



###################################################################################
# Checking lid state: if closed, set HDMI-1 as primary and initialize bspwm there
# otherwise initialize in eDP-1
###################################################################################
LID_STATE_FILE='/proc/acpi/button/lid/LID/state'
if grep 'open' $LID_STATE_FILE; then
    PRIMARY_DISPLAY='eDP-1'
else
    PRIMARY_DISPLAY='HDMI-1'
fi
export PRIMARY_DISPLAY

# setting primary
xrandr --output $PRIMARY_DISPLAY --primary
# switching off display with closed lid
if grep 'closed' $LID_STATE_FILE; then
    xrandr --output 'eDP-1' --off
fi
####################################################################################

sxhkd &
$XDG_CONFIG_HOME/polybar/launch.sh --hack
$XDG_CONFIG_HOME/wallpaper/launch.sh &

bspc monitor $PRIMARY_DISPLAY -d 1 2 3 4 5 6 7 8 9 0 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a 'Telegram Desktop' desktop='^3' state=fullscreen

