#!/usr/bin/sh



/usr/bin/wmname LG3D

###################################################################################
# Checking lid state: if closed, set HDMI-1 as primary and initialize bspwm there
# otherwise initialize in eDP-1
###################################################################################
LID_STATE_FILE='/proc/acpi/button/lid/LID/state'
if grep 'open' $LID_STATE_FILE; then
    PRIMARY_DISPLAY='eDP-1'
else
    PRIMARY_DISPLAY='HDMI-1'
fi
export PRIMARY_DISPLAY

# setting primary
xrandr --output $PRIMARY_DISPLAY --primary
# switching off display with closed lid
if grep 'closed' $LID_STATE_FILE; then
    xrandr --output 'eDP-1' --off
fi

xrandr --output $PRIMARY_DISPLAY -s 1920x1080 --mode 1920x1080


sxhkd &

compton --backend glx --paint-on-overlay --mark-ovredir-focused &
$XDG_CONFIG_HOME/polybar/launch.sh --blocks
$XDG_CONFIG_HOME/wallpaper/launch.sh &

bspc monitor $PRIMARY_DISPLAY -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a "ROOT" state=floating 
bspc rule -a "jetbrains-clion" state=floating desktop="^5" follow=on
bspc rule -a "zoom" state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a "Firefox:*:Picture-in-Picture" state=floating sticky

####################################################################################
# Keyboard layout
####################################################################################
pkill -9 kbdd
/usr/bin/kbdd

# localectl obviously resets xkbmap settings
#setxkbmap -model pc105 -layout us,ru -variant qwerty -option grp:win_space_toggle
localectl set-x11-keymap us,ru pc105 qwerty 'grp:win_space_toggle'

####################################################################################
# Lock screen at inactivity
####################################################################################
export XSECURELOCK_SWITCH_USER_COMMAND='dm-tool switch-to-greeter'

xset s on
xset s 120
/usr/bin/xss-lock -n $XDG_CONFIG_HOME/bspwm/xss-lock-hook.sh -- xsecurelock &

####################################################################################
# Calcurse
####################################################################################
/usr/bin/calcurse --daemon &
